id = "willow"
name = "Willow - TODO Highlighter"
version = "0.1.0"
schema_version = 1
authors = ["willibrandon <willibrandon@users.noreply.github.com>"]
description = "Universal TODO/FIXME/HACK highlighting for all languages using tree-sitter"
repository = "https://github.com/willibrandon/willow"

[lib]
path = "."