id = "willow"
name = "Willow"
version = "0.1.0"
schema_version = 1
authors = ["willibrandon <willibrandon@users.noreply.github.com>"]
description = "Universal TODO/FIXME/HACK highlighter for all languages"
repository = "https://github.com/willibrandon/willow"

[grammars.comment]
repository = "https://github.com/stsewd/tree-sitter-comment"
commit = "689be73775bd2dd57b938b8e12bf50fec35a6ca3"

[grammars.typescript]
repository = "https://github.com/tree-sitter/tree-sitter-typescript"
commit = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf"
path = "typescript"

[grammars.tsx]
repository = "https://github.com/tree-sitter/tree-sitter-typescript"
commit = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf"
path = "tsx"

languages = [
    "languages/comment",
    "languages/rust-injections",
    "languages/javascript-injections",
    "languages/typescript-injections",
    "languages/tsx-injections",
    "languages/python-injections",
    "languages/go-injections",
    "languages/c-injections",
    "languages/cpp-injections",
    "languages/java-injections",
    "languages/ruby-injections",
    "languages/bash-injections",
    "languages/yaml-injections",
    "languages/toml-injections",
    "languages/json5-injections",
    "languages/swift-injections",
    "languages/kotlin-injections",
    "languages/php-injections",
    "languages/c_sharp-injections",
    "languages/elixir-injections",
    "languages/haskell-injections"
]