id = "willow"
name = "Willow"
version = "0.1.0"
schema_version = 1
authors = ["willibrandon <willibrandon@users.noreply.github.com>"]
description = "Universal TODO/FIXME/HACK highlighter for all languages"
repository = "https://github.com/willibrandon/willow"

[grammars.comment]
repository = "https://github.com/stsewd/tree-sitter-comment"
commit = "689be73775bd2dd57b938b8e12bf50fec35a6ca3"

[grammars.typescript]
repository = "https://github.com/tree-sitter/tree-sitter-typescript"
commit = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf"
path = "typescript"

[grammars.tsx]
repository = "https://github.com/tree-sitter/tree-sitter-typescript"
commit = "b1bf4825d9eaa0f3bdeb1e52f099533328acfbdf"
path = "tsx"

[grammars.python]
repository = "https://github.com/tree-sitter/tree-sitter-python"
commit = "710796b8b877a970297106e5bbc8e2afa47f86ec"

[grammars.c_sharp]
repository = "https://github.com/tree-sitter/tree-sitter-c-sharp"
commit = "3431444351c871dffb32654f1299a00019280f2f"

[grammars.yaml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-yaml"
commit = "9e59b9bbf839ba231fbcb953617d8b9b9a059e38"

[grammars.kotlin]
repository = "https://github.com/fwcd/tree-sitter-kotlin"
commit = "57fb4560ba8641865bc0baa6b3f413b236112c4c"


[grammars.rust]
repository = "https://github.com/tree-sitter/tree-sitter-rust"
commit = "3691201b01cacb2f96ffca4c632c4e938bfacd88"

[grammars.go]
repository = "https://github.com/tree-sitter/tree-sitter-go"
commit = "5e73f476efafe5c768eda19bbe877f188ded6144"

[grammars.c]
repository = "https://github.com/tree-sitter/tree-sitter-c"
commit = "7fa1be1b694b6e763686793d97da01f36a0e5c12"

[grammars.cpp]
repository = "https://github.com/tree-sitter/tree-sitter-cpp"
commit = "5cb9b693cfd7bfacab1d9ff4acac1a4150700609"

[grammars.java]
repository = "https://github.com/tree-sitter/tree-sitter-java"
commit = "a7db5227ec40fcfe94489559d8c9bc7c8181e25a"

[grammars.ruby]
repository = "https://github.com/tree-sitter/tree-sitter-ruby"
commit = "89bd7a8e5450cb6a942418a619d30469f259e5d6"

[grammars.bash]
repository = "https://github.com/tree-sitter/tree-sitter-bash"
commit = "56b54c61fb48bce0c63e3dfa2240b5d274384763"

[grammars.toml]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-toml"
commit = "64b56832c2cffe41758f28e05c756a3a98d16f41"

[grammars.json5]
repository = "https://github.com/Joakker/tree-sitter-json5"
commit = "ab0ba8229d639ec4f3fa5f674c9133477f4b77bd"

[grammars.php]
repository = "https://github.com/tree-sitter/tree-sitter-php"
commit = "5b5627faaa290d89eb3d01b9bf47c3bb9e797dea"
path = "php"

[grammars.elixir]
repository = "https://github.com/elixir-lang/tree-sitter-elixir"
commit = "d24cecee673c4c770f797bac6f87ae4b6d7ddec5"

[grammars.haskell]
repository = "https://github.com/tree-sitter/tree-sitter-haskell"
commit = "0975ef72fc3c47b530309ca93937d7d143523628"

languages = [
    "languages/comment",
    "languages/rust-injections",
    "languages/javascript-injections",
    "languages/typescript-injections",
    "languages/tsx-injections",
    "languages/python-injections",
    "languages/go-injections",
    "languages/c-injections",
    "languages/cpp-injections",
    "languages/java-injections",
    "languages/ruby-injections",
    "languages/bash-injections",
    "languages/yaml-injections",
    "languages/toml-injections",
    "languages/json5-injections",
    "languages/kotlin-injections",
    "languages/php-injections",
    "languages/c_sharp-injections",
    "languages/elixir-injections",
    "languages/haskell-injections"
]